"""empty message

Revision ID: f6cd359cc7d6
Revises: ac7497a33e10
Create Date: 2020-09-28 16:12:38.332040

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f6cd359cc7d6'
down_revision = 'ac7497a33e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pledges', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('pledges', 'reated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pledges', sa.Column('reated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('pledges', 'created_at')
    # ### end Alembic commands ###
